#!/bin/bash
R="$(printf '\033[1;31m')"                           
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
B="$(printf '\033[1;34m')"
C="$(printf '\033[1;36m')"                                       
W="$(printf '\033[1;37m')"
BOLD="$(printf '\033[1m')"

clear
python3 $PREFIX/bin/photo.py $@
echo "${G}${BOLD} PRESS 1 TO ENTER SAFE MODE ....... "${W}
read -t 2 -n1 -s key
pkill -9 pulseaudio 
if [[ "$key" == "1" ]]; then
    echo "${G}${BOLD} Safe MODE DARKOS.....STARTING"${W}
    termux-x11 :0 &>/dev/null &
   # pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
  
   if [[ -f "/system/lib64/libskcodec.so" ]] ; then
  LD_PRELOAD="/system/lib64/libskcodec.so" pulseaudio --start --exit-idle-time=-1 &
  sleep 1
  pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1 

else
   pulseaudio --start --exit-idle-time=-1 &
   sleep 1
   pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
fi

    python3 $PREFIX/bin/darkos.py $@
    exit 0
elif [[ "$key" == " " ]]; then
    echo "${G}${BOLD} Booting DARKOS 🖤 "${W}
fi

old_version="0.971"
new_version=$(curl -s https://raw.githubusercontent.com/ahmad1abbadi/darkos/main/currently%20version.txt)

if ping -q -c 1 -W 1 google.com >/dev/null; then
    echo "${G}${BOLD} Welcome 🤗"${W}
    if awk 'BEGIN{exit !('$old_version' < '$new_version')}'; then
        echo ""
        echo "${G}${BOLD} update available ⏫....to version : ${C}${BOLD}$new_version"${W}
        sleep 3
else
        echo "${G}${BOLD} installed version : ${C}${BOLD}$old_version"${W}
        sleep 1
    fi
else
    echo "${G}${BOLD} no internet connection 😔🛜"${W}
fi

if [[ -v LD_PRELOAD ]]; then
    unset LD_PRELOAD
fi
echo ""
echo "${G}${BOLD} Booting DARKOS 🖤"${W}

termux-x11 :0 &>/dev/null &
#pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
if [[ -f "/system/lib64/libskcodec.so" ]] ; then
  LD_PRELOAD="/system/lib64/libskcodec.so" pulseaudio --start --exit-idle-time=-1 &
  sleep 1
  pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1 

else
   pulseaudio --start --exit-idle-time=-1 &
   sleep 1
   pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
fi

custom_darkos="$PREFIX/glibc/opt/darkos/custom_theme.txt"

if [ -f "$custom_darkos" ]; then
    export DISPLAY=:0
    startxfce4 &>/dev/null &
    python3 $PREFIX/glibc/opt/scripts/custom_style.py $@
else
    python3 $PREFIX/bin/run-darkos.py $@
fi
